name: tanventure-client-site
services:
- name: web
  github:
    repo: Dipro56/tanventure-client-site
    branch: main
    deploy_on_push: true
  
  source_dir: /
  environment_slug: node-js
  
  # Build process
  build_command: |
    echo "Starting build process..."
    npm install --legacy-peer-deps --no-audit --no-fund
    npm run build
    echo "Build completed successfully!"
  
  run_command: npm start
  
  # Environment
  instance_count: 1
  instance_size_slug: basic-xxs
  environment_variables:
  - key: NODE_ENV
    value: production
  - key: NEXT_TELEMETRY_DISABLED
    value: 1
  
  # Health check
  health_check:
    http_path: /
    initial_delay_seconds: 30
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3
  
  routes:
  - path: /
  http_port: 3000